namespace VketTools.Validator.RuleSets
{
    internal static class BuiltinShaderDatabase
    {
        // 2019.4.31f1 Unityビルトインシェーダー
        internal static readonly string[] UnityBuiltinShaderNames =
        {
            "GUI/Text Shader",
            "Hidden/InternalClear",
            "Hidden/Internal-Colored",
            "Hidden/InternalErrorShader",
            "Hidden/FrameDebuggerRenderTargetDisplay",
            "Legacy Shaders/Transparent/Bumped Diffuse",
            "Legacy Shaders/Transparent/Bumped Specular",
            "Legacy Shaders/Transparent/Diffuse",
            "Legacy Shaders/Transparent/Specular",
            "Legacy Shaders/Transparent/Parallax Diffuse",
            "Legacy Shaders/Transparent/Parallax Specular",
            "Legacy Shaders/Transparent/VertexLit",
            "Legacy Shaders/Transparent/Cutout/Bumped Diffuse",
            "Legacy Shaders/Transparent/Cutout/Bumped Specular",
            "Legacy Shaders/Transparent/Cutout/Diffuse",
            "Legacy Shaders/Transparent/Cutout/Specular",
            "Legacy Shaders/Transparent/Cutout/Soft Edge Unlit",
            "Legacy Shaders/Transparent/Cutout/VertexLit",
            "AR/TangoARRender",
            "Autodesk Interactive",
            "Hidden/Compositing",
            "Hidden/CubeBlend",
            "Hidden/CubeBlur",
            "Hidden/CubeBlurOdd",
            "Hidden/CubeCopy",
            "Legacy Shaders/Decal",
            "FX/Flare",
            "Hidden/GIDebug/ShowLightMask",
            "Hidden/GIDebug/TextureUV",
            "Hidden/GIDebug/UV1sAsPositions",
            "Hidden/GIDebug/VertexColors",
            "Legacy Shaders/Self-Illumin/Bumped Diffuse",
            "Legacy Shaders/Self-Illumin/Bumped Specular",
            "Legacy Shaders/Self-Illumin/Diffuse",
            "Legacy Shaders/Self-Illumin/Specular",
            "Legacy Shaders/Self-Illumin/Parallax Diffuse",
            "Legacy Shaders/Self-Illumin/Parallax Specular",
            "Legacy Shaders/Self-Illumin/VertexLit",
            "Hidden/BlitCopy",
            "Hidden/BlitCopyDepth",
            "Hidden/BlitCopyWithDepth",
            "Hidden/BlitToDepth",
            "Hidden/BlitToDepth_MSAA",
            "Hidden/Internal-CombineDepthNormals",
            "Hidden/ConvertTexture",
            "Hidden/Internal-CubemapToEquirect",
            "Hidden/Internal-DeferredReflections",
            "Hidden/Internal-DeferredShading",
            "Hidden/Internal-DepthNormalsTexture",
            "Hidden/Internal-Flare",
            "Hidden/Internal-GUIRoundedRect",
            "Hidden/Internal-GUIRoundedRectWithColorPerBorder",
            "Hidden/Internal-GUITexture",
            "Hidden/Internal-GUITextureBlit",
            "Hidden/Internal-GUITextureClip",
            "Hidden/Internal-GUITextureClipText",
            "Hidden/Internal-Halo",
            "Hidden/Internal-MotionVectors",
            "Hidden/Internal-ODSWorldTexture",
            "Hidden/Internal-PrePassLighting",
            "Hidden/Internal-ScreenSpaceShadows",
            "Hidden/Internal-StencilWrite",
            "Hidden/Internal-UIRAtlasBlitCopy",
            "Hidden/Internal-UIRDefault",
            "Legacy Shaders/Lightmapped/Bumped Diffuse",
            "Legacy Shaders/Lightmapped/Bumped Specular",
            "Legacy Shaders/Lightmapped/Diffuse",
            "Legacy Shaders/Lightmapped/Specular",
            "Legacy Shaders/Lightmapped/VertexLit",
            "Mobile/Bumped Diffuse",
            "Mobile/Bumped Specular (1 Directional Realtime Light)",
            "Mobile/Bumped Specular",
            "Mobile/Diffuse",
            "Mobile/Unlit (Supports Lightmap)",
            "Mobile/Particles/Additive",
            "Mobile/Particles/VertexLit Blended",
            "Mobile/Particles/Alpha Blended",
            "Mobile/Particles/Multiply",
            "Mobile/Skybox",
            "Mobile/VertexLit (Only Directional Lights)",
            "Mobile/VertexLit",
            "Nature/Tree Soft Occlusion Bark",
            "Hidden/Nature/Tree Soft Occlusion Bark Rendertex",
            "Nature/Tree Soft Occlusion Leaves",
            "Hidden/Nature/Tree Soft Occlusion Leaves Rendertex",
            "Nature/SpeedTree",
            "Nature/SpeedTree8",
            "Nature/SpeedTree Billboard",
            "Hidden/Nature/Tree Creator Albedo Rendertex",
            "Nature/Tree Creator Bark",
            "Hidden/Nature/Tree Creator Bark Optimized",
            "Hidden/Nature/Tree Creator Bark Rendertex",
            "Nature/Tree Creator Leaves",
            "Nature/Tree Creator Leaves Fast",
            "Hidden/Nature/Tree Creator Leaves Fast Optimized",
            "Hidden/Nature/Tree Creator Leaves Optimized",
            "Hidden/Nature/Tree Creator Leaves Rendertex",
            "Hidden/Nature/Tree Creator Normal Rendertex",
            "Legacy Shaders/Bumped Diffuse",
            "Legacy Shaders/Bumped Specular",
            "Legacy Shaders/Diffuse",
            "Legacy Shaders/Diffuse Detail",
            "Legacy Shaders/Diffuse Fast",
            "Legacy Shaders/Specular",
            "Legacy Shaders/Parallax Diffuse",
            "Legacy Shaders/Parallax Specular",
            "Legacy Shaders/VertexLit",
            "Legacy Shaders/Particles/Additive",
            "Legacy Shaders/Particles/~Additive-Multiply",
            "Legacy Shaders/Particles/Additive (Soft)",
            "Legacy Shaders/Particles/Alpha Blended",
            "Legacy Shaders/Particles/Anim Alpha Blended",
            "Legacy Shaders/Particles/Blend",
            "Legacy Shaders/Particles/Multiply",
            "Legacy Shaders/Particles/Multiply (Double)",
            "Legacy Shaders/Particles/Alpha Blended Premultiply",
            "Particles/Standard Surface",
            "Particles/Standard Unlit",
            "Legacy Shaders/Particles/VertexLit Blended",
            "Legacy Shaders/Reflective/Bumped Diffuse",
            "Legacy Shaders/Reflective/Bumped Unlit",
            "Legacy Shaders/Reflective/Bumped Specular",
            "Legacy Shaders/Reflective/Bumped VertexLit",
            "Legacy Shaders/Reflective/Diffuse",
            "Legacy Shaders/Reflective/Specular",
            "Legacy Shaders/Reflective/Parallax Diffuse",
            "Legacy Shaders/Reflective/Parallax Specular",
            "Legacy Shaders/Reflective/VertexLit",
            "Skybox/Cubemap",
            "Skybox/Panoramic",
            "Skybox/Procedural",
            "Skybox/6 Sided",
            "Sprites/Default",
            "Sprites/Diffuse",
            "Sprites/Mask",
            "Standard",
            "Standard (Specular setup)",
            "Hidden/TerrainEngine/Details/Vertexlit",
            "Hidden/TerrainEngine/Details/WavingDoublePass",
            "Hidden/TerrainEngine/Details/BillboardWavingDoublePass",
            "Hidden/TerrainEngine/Splatmap/Diffuse-AddPass",
            "Hidden/TerrainEngine/Splatmap/Diffuse-Base",
            "Hidden/TerrainEngine/Splatmap/Diffuse-BaseGen",
            "Nature/Terrain/Diffuse",
            "Hidden/TerrainEngine/Splatmap/Specular-AddPass",
            "Hidden/TerrainEngine/Splatmap/Specular-Base",
            "Nature/Terrain/Specular",
            "Hidden/TerrainEngine/Splatmap/Standard-AddPass",
            "Hidden/TerrainEngine/Splatmap/Standard-Base",
            "Hidden/TerrainEngine/Splatmap/Standard-BaseGen",
            "Nature/Terrain/Standard",
            "Hidden/Nature/Terrain/Utilities",
            "Hidden/TerrainEngine/BillboardTree",
            "Hidden/TerrainEngine/CameraFacingBillboardTree",
            "Hidden/TerrainEngine/BrushPreview",
            "Hidden/TerrainEngine/CrossBlendNeighbors",
            "Hidden/TerrainEngine/GenerateNormalmap",
            "Hidden/TerrainEngine/PaintHeight",
            "Hidden/TerrainEngine/HeightBlitCopy",
            "Hidden/TerrainEngine/TerrainLayerUtils",
            "Hidden/TextCore/Distance Field SSD",
            "Hidden/TextCore/Distance Field",
            "Hidden/UI/CompositeOverdraw",
            "UI/Default",
            "UI/DefaultETC1",
            "UI/Default Font",
            "UI/Lit/Bumped",
            "UI/Lit/Detail",
            "UI/Lit/Refraction",
            "UI/Lit/Refraction Detail",
            "UI/Lit/Transparent",
            "Hidden/UI/Overdraw",
            "UI/Unlit/Detail",
            "UI/Unlit/Text",
            "UI/Unlit/Text Detail",
            "UI/Unlit/Transparent",
            "Unlit/Transparent",
            "Unlit/Transparent Cutout",
            "Unlit/Color",
            "Unlit/Texture",
            "Hidden/VideoComposite",
            "Hidden/VideoDecode",
            "Hidden/VideoDecodeAndroid",
            "Hidden/VideoDecodeML",
            "Hidden/VideoDecodeOSX",
            "Hidden/VR/BlitFromTex2DToTexArraySlice",
            "Hidden/VR/BlitTexArraySlice",
            "Hidden/VR/BlitTexArraySliceToDepth",
            "Hidden/VR/BlitTexArraySliceToDepth_MSAA",
            "Hidden/VR/Internal-VRDistortion",
            "VR/SpatialMapping/Occlusion",
            "VR/SpatialMapping/Wireframe"
        };
    }
}